### ISSUE TITLE
GET A README

### ISSUE THREAD

**Issue by Bachmann1234** [citizenken/canvascast#3]
What is this?! I wanna see.

Hope things are going well

**Comment by citizenken** [comment]
Done. My other Chromecast experiment, storycast, is kind of more interesting. Its a version of the collaborative story game where each person writes a sentence of a story, knowing only the one preceding sentence. The Chromecast handles randomly picking who goes next and manages the story strings and displays the whole story when it is complete. I'm going to re-write it, make it better.
